from __future__ import annotations

from typing import Annotated, Any
from typing_extensions import TypedDict
import operator


# ── Supporting types ──────────────────────────────────────────────────────────

class SearchResult(TypedDict):
    """One result returned by Tavily for a single sub-question."""
    title: str
    content: str
    url: str
    score: float          # Tavily relevance score 0-1


class ResearchData(TypedDict):
    """Bundled search results for a single sub-question."""
    sub_question: str
    results: list[SearchResult]


class CritiqueDecision(TypedDict):
    """Structured output from the Critic node."""
    passed: bool                     # True  → go to Synthesizer
                                     # False → loop back to Researcher
    gaps: list[str]                  # issues found (empty if passed)
    refined_queries: list[str]       # replacement sub-questions (if not passed)
    reasoning: str                   # short explanation for the trace log


# ── Main state ────────────────────────────────────────────────────────────────

class AgentState(TypedDict):
    """
    Shared state object passed between every node.

    Annotation rules
    ────────────────
    - `Annotated[list, operator.add]`  → LangGraph *appends* new items
      instead of replacing the list. Used for sources so no node
      accidentally clobbers another node's data.
    - Plain types (str, int, bool, …)  → last-write wins (normal behaviour).
    """

    # ── Input ─────────────────────────────────────────────────────────────────
    query: str
    """The original raw query submitted by the user."""

    # ── Planner outputs ───────────────────────────────────────────────────────
    sub_questions: list[str]
    """3-5 focused sub-questions generated by the Planner node."""

    # ── Researcher outputs ────────────────────────────────────────────────────
    research_data: list[ResearchData]
    """Raw search results keyed by sub-question."""

    # ── Critic outputs ────────────────────────────────────────────────────────
    critique: CritiqueDecision | None
    """Latest critique decision. None until the Critic node runs."""

    critique_passed: bool
    """Convenience flag: True when Critic approved the research data."""

    iteration_count: int
    """Number of Critic → Researcher loops completed (max = MAX_CRITIC_ITERATIONS)."""

    # ── Synthesizer outputs ───────────────────────────────────────────────────
    final_report: str
    """Full markdown research report produced by the Synthesizer node."""

    confidence_score: int
    """Synthesizer's self-reported confidence 0-100."""

    sources: Annotated[list[str], operator.add]
    """
    Deduplicated list of source URLs cited in the final report.
    Uses operator.add annotation so each node can append without clobbering.
    """

    # ── Internal / metadata ───────────────────────────────────────────────────
    error: str | None
    """Non-None if any node encountered a recoverable error."""

    cache_hit: bool
    """True if the result was served from Redis rather than live API calls."""


# ── Default factory ───────────────────────────────────────────────────────────

def initial_state(query: str) -> AgentState:
    """
    Returns a fully-initialised AgentState for a new research job.

    Always use this factory instead of constructing the TypedDict by hand,
    so defaults stay in one place.

    Args:
        query: Raw user query string.

    Returns:
        AgentState with all fields set to safe zero-values.
    """
    return AgentState(
        query=query,
        sub_questions=[],
        research_data=[],
        critique=None,
        critique_passed=False,
        iteration_count=0,
        final_report="",
        confidence_score=0,
        sources=[],
        error=None,
        cache_hit=False,
    )
